app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'

urlpatterns = [

    # /app/
    url(r'^$', views.index, name = 'index'),

    # /app/<topic_id>/
    url(r'^(?P<topic_id>[0-9]+)/', views.detail, name = 'detail'),

    # /app/create_topic/
    url(r'^create_topic/$', views.create_topic, name = 'create_topic'),

    # /app/<topic_id>/add_requirement/<topic_id>
    url(r'^add_requirement/(?P<to_topic_id>[0-9]+)/(?P<from_topic_id>[0-9]+)/$', views.add_requirement, name = 'add_requirement'),

    # /app/delete_topic/
    url(r'^delete_topic/(?P<topic_id>[0-9]+)/$', views.delete_topic, name = 'delete_topic'),

    # /app/<topic_id>/edit_topic/
    url(r'^edit_topic/(?P<topic_id>[0-9]+)/$', views.edit_topic, name = 'edit_topic'),

    # /app/graph/
    url(r'^graph/$', views.graph, name = 'graph'),

    # /app/api/get_topics_as_json/
    url(r'^graph/api/get_topics_as_json/$', views.get_topics_as_json, name = 'get_topics_as_json'),

]

edupedia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('app.urls')),
]

app/models.py
# This file stores our representations of objects which will be stored in our database.

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User, Permission
from django.core.urlresolvers import reverse

class Topic(models.Model):
    user = models.ForeignKey(User, default=1)
    title = models.CharField(max_length=200, blank=False, null=False)
    content = models.TextField(default="Please add your content here")
    modified_content = models.TextField(default="Please add your content here")

    requirement_for = models.ForeignKey('self',
                                        related_name='is_requirement_for',
                                        null=True,
                                        blank=True,
                                        on_delete=models.CASCADE)

    main_requirement = models.ForeignKey('self',
                                         related_name='has_main_requirement',
                                         null=True,
                                         blank=True,
                                         on_delete=models.CASCADE)

    requirements = models.ManyToManyField('self',
                                          through='Requirement_Relation',
                                          blank=True,
                                          symmetrical=False,
                                          related_name='related_topic+')

    is_basic = models.BooleanField(default=False)
    is_first = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Requirement_Relation(models.Model):
    # ?! you might need to use these the other way around
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, related_name='for_topic')
    requirement = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, related_name='from_topic')

    class Meta:
        unique_together = ('topic', 'requirement')

app/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import Topic

class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['title', 'content', 'requirement_for', 'main_requirement', 'is_basic', 'is_first']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

app/views.py
# All of our views will live here, which are mapped to URLs.

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
import datetime
from .models import Topic, Requirement_Relation
from .forms import TopicForm
from django.core import serializers


def index(request):
    nav_bar = 'app/base_visitor.html'
    topics = Topic.objects.all()
    return render(request, 'app/index.html', {'topics': topics, 'nav_bar': nav_bar})

def detail(request, topic_id):
    topics = Topic.objects.all()
    user = request.user
    topic = get_object_or_404(Topic, pk=topic_id)
    return render(request, 'app/detail.html', {'topic': topic, 'topics': topics, 'user': user})

def change_requirements(topic):
    # if this is a requirement for something, put it into the main_requirement of that
    if topic.requirement_for:

        Topic.objects.filter(pk=topic.requirement_for.id).update(main_requirement=topic)

        # While the upper topic is not first, add this topic in upper topic's requirements
        up_topic = topic
        while up_topic.is_first == False:
            rel = Requirement_Relation(topic=up_topic.requirement_for, requirement=topic)
            rel.save()
            up_topic = up_topic.requirement_for

    # if this has a main_requirement, put it into the requirement_for of that
    if topic.main_requirement:

        Topic.objects.filter(pk=topic.main_requirement.id).update(requirement_for=topic)

        # add the requirement in the requirements of the topic
        rel = Requirement_Relation(topic=topic, requirement=topic.main_requirement)
        rel.save()

def create_topic(request):
    form = TopicForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        topic = form.save(commit=False)
        topic.user = request.user
        topic.save()

        change_requirements(topic)

        return render(request, 'app/detail.html', {'topic': topic, 'topic_id': topic.pk})

    context = {
        "form": form,
    }
    return render(request, 'app/create_topic.html', context)

def add_req_temp(request, to_topic_id, from_topic_id):
    print "Hello"
    nav_bar = 'app/base_visitor.html'
    topics = Topic.objects.all()
    return render(request, 'app/index.html', {'topics': topics, 'nav_bar': nav_bar})

def add_requirement(request, to_topic_id, from_topic_id):
    print "Adding requirement"
    user = request.user
    nav_bar = 'app/base_visitor.html'
    topics = Topic.objects.all()

    to_topic = get_object_or_404(Topic, pk=to_topic_id)
    from_topic = get_object_or_404(Topic, pk=from_topic_id)

    if Requirement_Relation.objects.filter(requirement=from_topic, topic=to_topic):
        error_message = "Requirement already exists."
        return render(request, 'app/detail.html', {'topic': to_topic, 'topics': topics, 'user': user, 'error_message': error_message})

    relation = Requirement_Relation(topic=to_topic, requirement=from_topic)
    relation.save()

    return render(request, 'app/detail.html', {'topic': to_topic, 'topics': topics, 'user': user})

def delete_topic(request, topic_id):
    nav_bar = "app/base_visitor.html"
    topic = Topic.objects.get(pk=topic_id)

    # Update the topics above and below the topic you want to delete
    Topic.objects.filter(main_requirement=topic).update(main_requirement=topic.main_requirement)
    Topic.objects.filter(requirement_for=topic).update(requirement_for=topic.requirement_for)

    # Set main_requirement and requirement_for to null, to avoid deleting multiple objects
    Topic.objects.filter(pk=topic_id).update(main_requirement=None, requirement_for=None)

    # Delete the relationships this object has to any other
    Requirement_Relation.objects.filter(topic=topic).delete() # Check if this works!
    Requirement_Relation.objects.filter(requirement=topic).delete() # Check if this works!

    topic.delete()
    topics = Topic.objects.filter(user=request.user)
    return render(request, 'app/index.html', {'topics': topics, 'nav_bar': nav_bar})

def edit_topic(request, topic_id):
    user = request.user
    topics = Topic.objects.all()
    topic = get_object_or_404(Topic, pk=topic_id)
    form = TopicForm(request.POST or None, instance=topic)

    if form.is_valid():
        topic = form.save(commit=False)
        topic.user = request.user
        topic.save()
        form.save_m2m()
        # change_requirements(topic)
        return render(request, 'app/detail.html', {'topic': topic, 'topics': topics, 'user': user})
        return HttpResponse('Topic was edited')

    context = {
        "form": form
    }
    return render(request, 'app/edit_topic.html', context)

def graph(request):
    nav_bar = 'app/base_visitor.html'
    return render(request, 'app/graph.html', {'nav_bar': nav_bar})

def get_topics_as_json(request):
    data = serializers.serialize('json', Topic.objects.all().order_by('id'))
    return HttpResponse(JsonResponse(data, safe=False), content_type="application/json")

edupedia/views.py
from django.http import HttpResponse

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Edupedia</title>

    <!-- Loads the path to static files -->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar" name="button">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'app:index' %}">Edupedia</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
          <form class="navbar-form navbar-left" role="search" method="get" action="#">
              <div class="form-group">
                  <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              <li class="{% block topics_active %}{% endblock %}" ><a href="{% url 'app:index' %}">My Learning</a></li>
              <li>
                  <a href="{% url 'app:create_topic' %}">
                      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create Topic
                  </a>
              </li>
              <li>
                  <a href="#">
                      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                  </a>
              </li>
          </ul>

        </div>

      </div>
    </nav>

<div class="wrapper">
  {% block body %}
  {% endblock %}
</div>

</body>
</html>

app/templates/app/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Edupedia{% endblock %}</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

  <!-- Always shows a header, even in smaller screens. -->
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header" id="topNavBar">
      <div class="mdl-layout__header-row">

        <!-- Title -->
        <a class="mdl-navigation__link mdl-layout-title" href="{% url 'app:index' %}">Edupedia</a>

        <!-- Add spacer, to align navigation to the right -->
        <div class="mdl-layout-spacer"></div>

        <!-- Search Bar -->
        <form role="search" method="get" action="{% url 'app:index' %}">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
              <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
                <i class="material-icons">search</i>
              </label>
              <div class="mdl-textfield__expandable-holder">
                <input class="mdl-textfield__input" type="text" id="search" name="q" value="{{ request.GET.q }}">
                <label class="mdl-textfield__label" for="search">What do you want to learn?</label>
              </div>
          </div>
        </form>

        <!-- Navigation. We hide it in small screens. -->
        <nav class="mdl-navigation mdl-layout--large-screen-only">
          <a class="mdl-navigation__link" href="{% url 'app:create_topic' %}">
            <button class="mdl-button mdl-js-button mdl-button--icon">
              <i class="material-icons">add</i>
            </button>
          </a>
        </nav>
      </div>
    </header>

    <!-- Drawer Navigation -->
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title">Edupedia</span>
      <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="{% url 'app:index' %}">Discover Topics</a>
        <a class="mdl-navigation__link" href="{% url 'app:create_topic' %}">Create Topic</a>
        <a class="mdl-navigation__link" href="{% url 'app:graph' %}">Map of Knowledge</a>
        <div class="mdl-layout-spacer"></div>
      </nav>
    </div>

    <!-- Page Content -->
    <main class="mdl-layout__content">
      <div class="page-content">
        {% block body %}
        {% endblock %}
      </div>

      <!-- Footer -->
      <footer class="demo-footer mdl-mini-footer">
        <div class="mdl-mini-footer--left-section">
          <ul class="mdl-mini-footer--link-list">
            <li><a href="#">Help</a></li>
            <li><a href="">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
      </footer>
    </main>
  </div>

</body>
</html>

app/templates/app/create_topic.html
{% extends 'app/base_visitor.html' %}
{% block title %}Add a New Topic{% endblock %}
{% block topics_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Topic</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'app/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

app/templates/app/detail.html
{% extends 'app/base_visitor.html' %}

{% block body %}

<div class="demo-ribbon"></div>

<div class="demo-container mdl-grid">

  <div class="mdl-cell mdl-cell--1-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>

  <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--10-col topic-wrapper">
    <h1>{{ topic.title }}</h1>
    <p>By {{ topic.user.username }}</p>

    <!-- If statement for showing an error message -->
    {% if error_message %}
      <p style="color:red; font-size:24px">
        <strong>Error: {{ error_message }}</strong>
      </p>
    {% endif %}

    <!-- Overview of the topic -->
    <div class="overview-wrapper">
      <div class="row">

        {% if topic.is_basic != True %}

        <div class="col-md-12 text-left overview">
          <h3>Before {{ topic.title }}...</h3>
          <p>You're on your way to mastering {{ topic.title }}, but first you should take a look at:</p>
          <ul>

            {% if topic.main_requirement %}

            <li class="topic-requirement">
              <span class="circle"></span>
              <a href="{% url 'app:detail' topic.main_requirement.id %}">
                <h3>{{ topic.main_requirement.title }}</h3>
              </a>
            </li>

            {% endif %}

          </ul>

          <div class="dropdown show all-requirements">
            <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-menu-down"></span>&nbsp;See everything you need to know
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

              {% for req in topic.requirements.all %}
                  <a href="{% url 'app:detail' req.id %}" class="dropdown-item">
                    <p>{{ req.title }}</p>
                  </a>
              {% endfor %}

            </div>

          </div>

        </div>

        {% else %}

        <div class="col-md-12 text-left overview">
          <h3>Start with {{ topic.title }} and work your way up to </h3>
        </div>

        {% endif %}

        <div class="col-md-12 text-left overview">
          <h3>What is {{ topic.title }}?</h3>
          <p>
            {{ topic.content }}
          </p>
        </div>

        {% if topic.is_first != True %}

          {% if topic.requirement_for %}

            <div class="col-md-12 text-left overview">
              <h3>After {{ topic.title }}...</h3>
              <p>Congratulations! You can now dive into
                <a href="{% url 'app:detail' topic.requirement_for.id %}">{{ topic.requirement_for.title }}</a>
              </p>
            </div>

          {% else %}

            <div class="col-md-12 text-left overview">
              <h3>Uups..</h3>
              <p>There is no parent of this topic topic.</p>
              <a href="{% url 'app:create_topic' %}">
                <button type="button" class="btn btn-success">
                  <span class="glyphicon glyphicon-plus"></span>&nbsp; Add requirement_for
                </button>
              </a>
            </div>

          {% endif %}

        {% else %}

          <div class="col-md-12 text-left overview">
            <h3>Amazing!</h3>
            <p>If you've gone through all the requirements, you've mastered {{ topic.title }}</p>
          </div>

        {% endif %}

      </div>


        {% if topic.is_basic != True %}

        <div class="row add-requirements">
          <div class="col-sm-8 text-left">
            <h3>What else do you think is required to know {{ topic.title }}?</h3>
            <br>
            <div class="dropdown show">
              <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-menu-down"></span>&nbsp; Add Requirements
              </button>
              <!-- Left aligned menu below button -->
              <div class="bar">
                <button id="demo-menu-lower-left"
                        class="mdl-button mdl-js-button mdl-button--icon">
                  <i class="material-icons">more_vert</i>
                </button>
                Add Requirements
                <ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
                    for="demo-menu-lower-left">
                  {% for req in topics %}
                  <li class="mdl-menu__item">
                    <a href="{% url 'app:add_requirement' topic.id req.id %}" class="dropdown-item">
                      <p>{{ req.title }}</p>
                    </a>
                  </li>
                  {% endfor %}
                </ul>
              </div>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                {% for req in topics %}
                    <a href="{% url 'app:add_requirement' topic.id req.id %}" class="dropdown-item">
                      <p>{{ req.title }}</p>
                    </a>
                {% endfor %}

              </div>
            </div>
          </div>
        </div>

        {% endif %}

    </div>

  </div>
</div>

<a href="{% url 'app:edit_topic' topic.id %}" id="edit-page" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--accent mdl-color-text--accent-contrast" data-upgraded=",MaterialButton,MaterialRipple">
  Edit Page
  <span class="mdl-button__ripple-container">
    <span class="mdl-ripple is-animating" style="width: 258.5px; height: 258.5px; transform: translate(-50%, -50%) translate(13px, 13px);"></span>
  </span>
</a>

{% endblock %}

app/templates/app/index-bootstrap-styling.html
{% extends nav_bar %}
{% block topics_active %}active{% endblock %}

{% block body %}

<div class="mdl-gen mdl-cell mdl-cell--12-col">
  <h2>This is a 12 col grid</h2>
  <div class="mdl-grid">
    <div class="mdl-gen__panel mdl-gen__panel--left mdl-cell mdl-cell--6-col-desktop mdl-cell--8-col">
      <h4>6 col inside</h4>
      <div id="wheel">
        <div class="mdl-gen-download">
          <h1>Hello</h1>
          <p>
            Lorem ipsum dolor sit amet, dicam salutatus vulputate at has, cum nullam facilisis ei. Omnium referrentur cum eu, ex sale sanctus admodum eum. Amet imperdiet ad sit. In mei omittam facilisi persecuti, mandamus perpetua torquatos mel cu.
            Te qui dolore soleat nonumes. Reque omnes aliquando mei no, ut nonumes propriae eam. Utamur consulatu temporibus ei eos, ei dicta labore gloriatur sit. Sit id virtute pericula, pri habeo nominati et.
          </p>
          <a href="#" id="download" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--fab"><i class="material-icons">file_download</i></a>
        </div>
      </div>
    </div>
    <div class="mdl-gen__panel--right mdl-gen__panel mdl-cell mdl-cell--4-col-desktop mdl-cell--8-col">
      <h4>Another 4 col</h4>
      <div class="mdl-gen__desc docs-text-styling">
        <h1>Hello</h1>
        <p>
          Lorem ipsum dolor sit amet, dicam salutatus vulputate at has, cum nullam facilisis ei. Omnium referrentur cum eu, ex sale sanctus admodum eum. Amet imperdiet ad sit. In mei omittam facilisi persecuti, mandamus perpetua torquatos mel cu.
          Te qui dolore soleat nonumes. Reque omnes aliquando mei no, ut nonumes propriae eam. Utamur consulatu temporibus ei eos, ei dicta labore gloriatur sit. Sit id virtute pericula, pri habeo nominati et.
        </p>
        <a href="#" id="download" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--fab"><i class="material-icons">file_download</i></a>
      </div>
      <div class="mdl-gen__preview">
      </div>
    </div>
  </div>
</div>


<div class="container-fluid topic-wrapper">

  <div class="col-sm-12">
    {% if not user.username or request.path == "/app/discover/" %}
      <h1>Discover Topics</h1>
    {% else %}
      <h1>Your Topics</h1>
    {% endif %}
  </div>

  <!-- Topics -->
  <div class="container">
    <div class="row">

      {% if topics %}

          {% for topic in topics %}

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

              <div class="topic-container">
                <div class="requirement-info">
                    <!-- View requirements for topic -->
                    {% if user.username %}
                      <a href="{% url 'app:detail' topic.id %}">
                        {{ topic.title }}
                      </a>
                    {% else %}
                      <a href="{% url 'app:detail' topic.id %}">
                        {{ topic.title }}
                      </a>
                    {% endif %}
                </div>

                <!-- Delete topic (Only if logged in) -->
                {% if user.username == topic.user.username %}
                  <form action="{% url 'app:delete_topic' topic.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="topic_id" value="{{ topic.id }}" />
                    <button type="submit" class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect mdl-button--colored">
                      <i class="material-icons">delete</i>
                    </button>
                  </form>
                {% endif %}


              </div>

            </div>

          {% endfor %}

      {% else %}
        <div class="col-sm-12">
          <br>
          <a href="{% url 'app:create_topic' %}">
            <button type="button" class="btn btn-success">
              <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Topic
            </button>
          </a>
        </div>
      {% endif %}

    </div>
  </div>

  <!-- If user searches and there subtopics, display them -->
  {% if sub_topics %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Sub Topics</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Subtopics</th>
                                    <th>Part of</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for sub_topic in sub_topics %}
                                    <tr>
                                        <td>{{ sub_topic.title }}</td>
                                        <td>{{ sub_topic.requirements }}</td>
                                        <td>
                                            <a href="{% url 'app:detail' sub_topic.topic.id %}">{{ sub_topic.topic.title }}</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>

{% endblock %}

app/templates/app/index.html
{% extends nav_bar %}
{% block topics_active %}active{% endblock %}

{% block body %}

<div class="content-grid mdl-grid"> <!-- Start Grid -->

    <div class="mdl-grid"> <!-- Topics Grid -->

      <div class="mdl-gen mdl-cell mdl-cell--12-col title-cell">
        {% if not user.username or request.path == "/app/discover/" %}
          <h1>Discover Topics</h1>
        {% else %}
          <h1>Your Topics</h1>
        {% endif %}
      </div>

      {% if topics %}

          {% for topic in topics %}

              <!-- Square topic card -->
              <div class="mdl-gen mdl-cell mdl-cell--4-col-desktop mdl-cell--4-col-tablet mdl-cell--4-col-phone topic-container">
                <div class="demo-card-square mdl-card mdl-shadow--2dp">
                  <div class="mdl-card__title mdl-card--expand">
                    <h2 class="mdl-card__title-text">{{ topic.title }}</h2>
                  </div>
                  <div class="mdl-card__supporting-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Aenan convallis.
                  </div>
                  <div class="mdl-card__actions mdl-card--border">
                    <!-- View details of topic -->
                    <a href="{% url 'app:detail' topic.id %}" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                      View Details
                    </a>
                    <!-- Delete topic (Only if logged in) -->
                    {% if user.username == topic.user.username %}
                      <form action="{% url 'app:delete_topic' topic.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="topic_id" value="{{ topic.id }}" />
                        <button type="submit" class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect mdl-button--colored">
                          <i class="material-icons">delete</i>
                        </button>
                      </form>
                    {% endif %}
                  </div>
                </div>
              </div>

          {% endfor %}

      {% else %}
        <div class="mdl-gen mdl-cell mdl-cell--12-col">
          <br>
          <a href="{% url 'app:create_topic' %}">
            <button type="button" class="btn btn-success">
              <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Topic
            </button>
          </a>
        </div>
      {% endif %}

    </div> <!-- End Topics Grid -->

  <!-- If user searches and there subtopics, display them -->
  {% if sub_topics %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Sub Topics</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Subtopics</th>
                                    <th>Part of</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for sub_topic in sub_topics %}
                                    <tr>
                                        <td>{{ sub_topic.title }}</td>
                                        <td>{{ sub_topic.requirements }}</td>
                                        <td>
                                            <a href="{% url 'app:detail' sub_topic.topic.id %}">{{ sub_topic.topic.title }}</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div> <!-- End Grid -->

{% endblock %}